version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_api_container
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app-net

  redis:
    image: redis
    container_name: redis_container
    restart: always
    command: redis-server --requirepass 123
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis/data:/bitnami/redis/data
    networks:
      - app-net

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy_container
    command:
      - serve
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - ${NOTIFICATION_PORT}:80
    networks:
      - app-net

volumes:
  pgdata:
  redis:
  ntfy:

networks:
  app-net:
    driver: bridge